// Spruch-Datenbank für die NVV "Spruch des Tages"-App.
// Fiktive Norddeutsche Verbund-Versicherung AG.

window.NVV_QUOTES = [
  {
    nr: 1,
    text: "Wer den Antrag nicht in dreifacher Ausfertigung einreicht, hat den Antrag nicht eingereicht.",
    autor: "Reinhard Möller",
    rolle: "Abteilungsleiter Sachversicherung Nord-Ost",
    btr: "32 Jahre Betriebszugehörigkeit",
    kategorie: "Verfahrensordnung",
    az: "NVV-SDT-2026/0421-A",
    likes: 47, kommentare: 12, weiterleitungen: 4,
  },
  {
    nr: 2,
    text: "Eine Excel-Tabelle, die korrekt formatiert ist, kann durch keine Realität widerlegt werden.",
    autor: "Brigitte Schwanenberg",
    rolle: "Sachbearbeiterin Innenrevision",
    btr: "27 Jahre Betriebszugehörigkeit",
    kategorie: "Werkzeuge & Methoden",
    az: "NVV-SDT-2026/0420-B",
    likes: 89, kommentare: 23, weiterleitungen: 31,
  },
  {
    nr: 3,
    text: "Die Klimaanlage ist auf 21,0 °C eingestellt. Das ist nicht verhandelbar.",
    autor: "Hausverwaltung",
    rolle: "Liegenschaftsmanagement Hauptverwaltung",
    btr: "seit 1986 zuständig",
    kategorie: "Hausordnung",
    az: "NVV-SDT-2026/0419-T",
    likes: 156, kommentare: 78, weiterleitungen: 9,
  },
  {
    nr: 4,
    text: "Wer den Drucker neu startet, übernimmt damit auch die Verantwortung für die Toner-Bestellung im laufenden Quartal.",
    autor: "Hans-Werner Pott",
    rolle: "Bürotechnik-Beauftragter Etage 4",
    btr: "ehrenamtlich seit 2009",
    kategorie: "Bürotechnik",
    az: "NVV-SDT-2026/0418-K",
    likes: 64, kommentare: 18, weiterleitungen: 2,
  },
  {
    nr: 5,
    text: "Die Mittagspause beginnt um 12:00 Uhr. Nicht 11:58. Nicht 12:02. Wir sind hier nicht in der Privatwirtschaft.",
    autor: "Personalrat",
    rolle: "Vorsitz, Gremium 7-A",
    btr: "vereinsmäßig organisiert",
    kategorie: "Arbeitszeitordnung",
    az: "NVV-SDT-2026/0417-P",
    likes: 203, kommentare: 41, weiterleitungen: 17,
  },
  {
    nr: 6,
    text: "Ein Meeting ohne Tagesordnung ist juristisch betrachtet kein Meeting, sondern eine Begegnung.",
    autor: "Dr. jur. Friedhelm Quasthoff",
    rolle: "Justiziariat / Compliance",
    btr: "promoviert 1993",
    kategorie: "Sitzungsrecht",
    az: "NVV-SDT-2026/0416-J",
    likes: 71, kommentare: 9, weiterleitungen: 6,
  },
  {
    nr: 7,
    text: "Heute ist Brückentag. Wer arbeitet, hat den eigentlichen Sinn von Brücken nicht verstanden.",
    autor: "Ulrich Sasse",
    rolle: "Bereichsleitung Lebensversicherung",
    btr: "seit 1998 abwesend zwischen den Feiertagen",
    kategorie: "Lebensphilosophie",
    az: "NVV-SDT-2026/0415-L",
    likes: 412, kommentare: 88, weiterleitungen: 124,
  },
  {
    nr: 8,
    text: "Der Aktenschrank ist alphabetisch geordnet. Wer das nicht respektiert, respektiert auch das Versicherungsvertragsgesetz nicht.",
    autor: "Annegret Tönnies-Brakelmann",
    rolle: "Archivverwaltung KG-2",
    btr: "Archivarin im 24. Dienstjahr",
    kategorie: "Ablageordnung",
    az: "NVV-SDT-2026/0414-A",
    likes: 38, kommentare: 5, weiterleitungen: 1,
  },
  {
    nr: 9,
    text: "Die Kantine hat heute Königsberger Klopse. Das ist der eigentliche Spruch des Tages.",
    autor: "Frau Heidenreich",
    rolle: "Küchenleitung Casino Süd",
    btr: "seit 1991 am Herd",
    kategorie: "Verpflegung",
    az: "NVV-SDT-2026/0413-V",
    likes: 287, kommentare: 64, weiterleitungen: 12,
  },
  {
    nr: 10,
    text: "Wer eine E-Mail mit \u201eMit freundlichen Gr\u00fc\u00dfen\u201c abschlie\u00dft, hat den Vorgang abgeschlossen. Alles Weitere ist Privatkorrespondenz.",
    autor: "Manfred Buschhaus",
    rolle: "Schadensregulierung Kfz / Teilkasko",
    btr: "29 Jahre Betriebszugehörigkeit",
    kategorie: "Korrespondenzführung",
    az: "NVV-SDT-2026/0412-S",
    likes: 92, kommentare: 14, weiterleitungen: 8,
  },
  {
    nr: 11,
    text: "Eine ungefüllte Reisekostenabrechnung ist kein Formular. Sie ist eine offene Frage an den Steuerzahler.",
    autor: "Helga Vorwerk",
    rolle: "Reisekostenabteilung / Buchhaltung 3",
    btr: "Prokura seit 2011",
    kategorie: "Reisekosten",
    az: "NVV-SDT-2026/0411-R",
    likes: 53, kommentare: 11, weiterleitungen: 3,
  },
  {
    nr: 12,
    text: "Der Posteingang vom Freitag, 15:00 Uhr, gilt als Posteingang vom Montag. So wurde es immer gehandhabt.",
    autor: "Poststelle",
    rolle: "Posteingangsprüfung",
    btr: "Schichtdienst rotierend",
    kategorie: "Geschäftsgang",
    az: "NVV-SDT-2026/0410-G",
    likes: 134, kommentare: 27, weiterleitungen: 5,
  },
];

window.NVV_KOMMENTARE = [
  { autor: "Bernd Lütkemeyer", rolle: "Sachbearbeitung Hausrat", zeit: "08:14",
    text: "Nicht falsch. Erinnert mich an meinen ersten Vorgesetzten 1997. Der hat das genauso gehandhabt." },
  { autor: "Petra Achterkamp", rolle: "Innendienst Lebensversicherung", zeit: "08:31",
    text: "Bitte nicht weiterleiten an Etage 6. Dort wird das ernst genommen." },
  { autor: "Dr. F. Quasthoff", rolle: "Justiziariat", zeit: "09:02",
    text: "Aus juristischer Sicht zutreffend, sofern keine abweichende Betriebsvereinbarung greift. Vgl. § 12 Abs. 3 BV-Allg." },
  { autor: "Karl-Heinz Brömmel", rolle: "Empfang & Pförtnerei", zeit: "09:47",
    text: "👍" },
  { autor: "Ute Weber-Ostendorf", rolle: "Personalentwicklung", zeit: "10:18",
    text: "Wir nehmen den Spruch in den nächsten Onboarding-Foliensatz auf. Danke an die Redaktion." },
  { autor: "Anonym (verifiziert)", rolle: "Kostenstelle 4711", zeit: "11:55",
    text: "Hier wird zu viel gelacht. Und Lachen ist im Großraumbüro ab 17 dB ein meldepflichtiger Vorgang." },
];

window.NVV_NAV = [
  { sect: "Mein Arbeitsplatz", items: [
    { ic: "▦", l: "Übersicht" },
    { ic: "✉", l: "Posteingang", badge: 247 },
    { ic: "❑", l: "Aufgaben", badge: 18 },
    { ic: "★", l: "Spruch des Tages", active: true },
  ]},
  { sect: "Vorgänge", items: [
    { ic: "≡", l: "Schadensmeldungen" },
    { ic: "≡", l: "Kfz-Versicherung" },
    { ic: "≡", l: "Hausrat & Gebäude" },
    { ic: "≡", l: "Lebens­versicherung" },
    { ic: "≡", l: "Rechtsschutz" },
  ]},
  { sect: "Verwaltung", items: [
    { ic: "⌘", l: "Reisekosten" },
    { ic: "⌘", l: "Urlaubsantrag" },
    { ic: "⌘", l: "Krankmeldung" },
    { ic: "⌘", l: "Betriebsrat" },
  ]},
  { sect: "Auswertung", items: [
    { ic: "▤", l: "Tagesreport" },
    { ic: "▤", l: "Quartals­übersicht" },
  ]},
];
